const path = require('path')
const { copyDir, copyFile, checkDest } = require('./copyUtils')
const BASE_DIR = process.cwd()
let src1 = path.join(BASE_DIR + '/node_modules/axios/dist/')
let src2 = path.join(BASE_DIR + '/node_modules/axios/lib/')
let src3 = path.join(BASE_DIR + '/node_modules/axios/README.md')
let dest1 = path.join(BASE_DIR + '/public/axiosdist')
let dest2 = path.join(BASE_DIR + '/src/components/axioslib')
let dest3 = path.join(BASE_DIR + '/public')
checkDest(src1, dest1, copyDir)
checkDest(src2, dest2, copyDir)
checkDest(src3, dest3, copyFile)
